stages:
    - build


variables:
  DOCKER_DOMAIN: "246015105378.dkr.ecr.cn-north-1.amazonaws.com.cn"


build:image:
    stage: build
    only:
        - master
    tags:
        - beijing
        - docker_build
    variables:
        IMAGE_TAG: "${DOCKER_DOMAIN}/test/cyclops:latest"
    script:
        - docker build -t "${IMAGE_TAG}" .
        - docker push "${IMAGE_TAG}"


